/*amd /user/ReservationComplete.xml 3085 36776677855ec634c33515759d2ce492c3d7389537b2f5dd50260796e5648e4d */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'w2:MSA'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'}},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{lazy:'false',type:'text/javascript'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){scwin.onpageload = function () {};

// ダッシュボードへボタン押下
scwin.btn_goToDashboard_onclick = function (e) {
  $w.url("/user/Dashboard.xml");
};

// 予約履歴を確認するボタン押下（マイページへ）
scwin.btn_goToMyPage_onclick = function (e) {
  $w.url("/user/MyPage.xml");
};
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload'},E:[{T:1,N:'xf:group',A:{style:'display: flex; flex-direction: column; min-height: 100vh;',id:'grp_wrapper'},E:[{T:1,N:'w2:wframe',A:{id:'wfm_header',src:'/components/Header.xml',style:'width: 100%; min-height: 60px;'}},{T:1,N:'xf:group',A:{style:'display: flex; flex: 1;',id:'grp_body'},E:[{T:1,N:'w2:wframe',A:{id:'wfm_sidebar',src:'/components/Sidebar.xml',style:'width: 220px; min-height: 100%;'}},{T:1,N:'xf:group',A:{style:'padding: 20px; flex: 1; display: flex; flex-direction: column; align-items: center; background-color: #f8f9fa;',id:'grp_container'},E:[{T:1,N:'xf:group',A:{style:'width: 100%; max-width: 600px;',id:'grp_content'},E:[{T:1,N:'w2:textbox',A:{tagname:'h2',id:'txt_pageTitle',label:'予約完了',style:'margin-top: 0; margin-bottom: 20px; color: #333;'}},{T:1,N:'xf:group',A:{style:'background-color: #fff; padding: 40px 24px; border-radius: 8px; border: 1px solid #ddd; text-align: center;',id:'grp_card'},E:[{T:1,N:'w2:textbox',A:{tagname:'h3',id:'txt_completeMsg',label:'予約が完了いたしました！',style:'margin-top: 0; color: #28a745; font-size: 22px; margin-bottom: 16px;'}},{T:1,N:'w2:textbox',A:{tagname:'p',id:'txt_subMsg',label:'ご予約ありがとうございました。マイページより予約の確認が行えます。',style:'font-size: 15px; color: #555; margin-bottom: 32px;'}},{T:1,N:'xf:group',A:{style:'display: flex; gap: 16px; justify-content: center;',id:'grp_buttons'},E:[{T:1,N:'xf:trigger',A:{type:'button',id:'btn_goToDashboard',style:'padding: 10px 24px; background-color: #6c757d; color: #fff; font-size: 15px; border: none; border-radius: 4px; cursor: pointer;','ev:onclick':'scwin.btn_goToDashboard_onclick'},E:[{T:1,N:'xf:label',E:[{T:4,cdata:'ダッシュボードへ'}]}]},{T:1,N:'xf:trigger',A:{type:'button',id:'btn_goToMyPage',style:'padding: 10px 24px; background-color: #007bff; color: #fff; font-size: 15px; font-weight: bold; border: none; border-radius: 4px; cursor: pointer;','ev:onclick':'scwin.btn_goToMyPage_onclick'},E:[{T:1,N:'xf:label',E:[{T:4,cdata:'予約履歴を確認する'}]}]}]}]}]}]}]}]}]}]}]})